config/routes.rb
Rails.application.routes.draw do
  # get "/rooms" => "rooms#index"
  # post "/rooms" => "rooms#new"
  # get "/rooms/:id" => "rooms#show"
  # post "/rooms" => "room#create"
  # patch "/rooms/:id" => "rooms#update"
  # delete "/rooms/:id" => "rooms#destroy"
  # get "/rooms/:id/edit" => "rooms#edit"  


  # get "/reservations" => "reservations#index"
  # post "/reservations" => "reservations#new"
  # get "/reservations/:id" => "reservations#show"
  # post "/reservations" => "reservations#create"
  # patch "/reservations/:id" => "reservations#update"
  # delete "/reservations/:id" => "reservations#destroy"

  # get "/reviews" => "reviews#index"
  get "/reviews" => "reviews#new"
  # get "/reviews/:id" => "reviews#show"
  post "/reviews" => "reviews#create"
  # patch "/reviews/:id" => "reviews#update"
  # delete "/reviews/:id" => "reviews#destroy"

  # get "/room_images" => "room_images#index"
  # post "/room_images" => "room_images#new"
  # get "/room_images/:id" => "room_images#show"
  # post "/room_images" => "room_images#create"
  # patch "/room_images/:id" => "room_images#update"
  # delete "/room_images/:id" => "room_images#destroy"

  resources :rooms
  # resources :rooms do
  #   get 'reservations', on: :member
  #   post 'create_reservation', on: :member
  # end
  get "/rooms/:id/reservations" => "rooms#reservations"
  post "/rooms/:id/reservations" => "rooms#create_reservation"

  resources :rooms do
    get 'reservations', on: :member
    post 'create_reservation', on: :member
  end
  resources :rooms
  post "/rooms/:id/reservations" => "rooms#create_reservation"

# SIGNUP
  get "/signup" => "users#new"
  post "/users" => "users#create"

# LOGIN
  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"  

  
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :room_images, dependent: :destroy
  has_many :reservations, dependent: :destroy

  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :total_occupancy, presence: true
  validates :total_bedrooms, presence: true
  validates :total_bathrooms, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController


# RESERVATIONS 
# The reservations action finds the room that the user wants to reserve and initializes a new Reservation instance variable. It then renders the reservations.html.erb view, which displays a form for creating a new reservation.
  def reservations 
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

# CREATE RESERVATIONS
#The create_reservation action finds the room that the user wants to reserve, builds a new Reservation instance based on the form parameters, sets the user_id attribute to the current user's ID, and then tries to save the reservation to the database. If the reservation is successfully saved, the user is redirected to the show action for the reservation. Otherwise, the reservations.html.erb view is rendered again.
  def create_reservation
    @room = Room.find(params[:id])
    @reservation = Reservation.new(
      start_date: params[:start_date],
      end_date: params[:end],
    )
  
    @reservation.user_id = current_user.id
    if @reservation.save
      redirect_to "/rooms", notice: "Reservation was successfully created"
    else
      render 'reservations'
    end
  end    


# NEW
  def new
    @room = Room.new
  end

# INDEX
  def index 
  # Only display rooms that dont have any reservations
    if current_user
      @rooms = Room.left_outer_joins(:reservations).where(reservations: { id: nil })
    else
      @rooms = Room.all 
    end
    render "index", rooms: @rooms
  end

# CREATE
  def create 
    @room = current_user.rooms.new(
      address: params[:room][:address],
      city: params[:room][:city],
      state: params[:room][:state],
      price: params[:room][:price],
      description: params[:room][:description],
      home_type: params[:room][:home_type],
      room_type: params[:room][:room_type],
      total_occupancy: params[:room][:total_occupancy],
      total_bedrooms: params[:room][:total_bedrooms],
      total_bathrooms: params[:room][:total_bathrooms]
    )
    @room.save
    redirect_to "/rooms"
  end

# SHOW
  def show 
    @room = Room.find(params[:id])
    render :show
  end

# EDIT
  def edit
    @room = Room.find(params[:id])
    render :edit 
  end

# UPDATE
  def update 
    @room = Room.find(params[:id])
    @room.update(
      address: params[:room][:address],
      city: params[:room][:city],
      state: params[:room][:state],
      price: params[:room][:price],
      description: params[:room][:description],
      home_type: params[:room][:home_type],
      room_type: params[:room][:room_type],
      total_occupancy: params[:room][:total_occupancy],
      total_bedrooms: params[:room][:total_bedrooms],
      total_bathrooms: params[:room][:total_bathrooms]
    )

    redirect_to "/rooms"
  end

# DELETE/DESTROY
  def destroy
    @room = Room.find(params[:id])
    if @room.user == current_user
      @room.destroy
      redirect_to rooms_path, notice: "Room was successfully deleted"
    else
      redirect_to rooms_path, notice: "You are not authorized to delete this room"
    end
  end



private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<!-------------EDIT/UPDATE----------------->
<h1>Edit Room</h1>
<%= form_with model: @room do |form| %>
  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  <div>
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>
  <div>
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :home_type %>
    <%= form.text_field :home_type %>
  </div>
  <div>
    <%= form.label :room_type %>
    <%= form.text_field :room_type %>
  </div>
  <div>
    <%= form.label :total_occupancy %>
    <%= form.number_field :total_occupancy %>
  </div>
  <div>
    <%= form.label :total_bedrooms %>
    <%= form.number_field :total_bedrooms %>
  </div>
  <div>
    <%= form.label :total_bathrooms %>
    <%= form.number_field :total_bathrooms %>
  </div>
  <%= form.submit %>
<% end %>

app/views/rooms/index.html.erb
<h1>All Rooms</h1>
<% @rooms.each do |room| %>
  <h2><%= room.address %></h2>
  <p>Price: <%= room.price %></p>
  <p>Description: <%= room.description %></p>
  <a href="/rooms/<%= room.id %>">More info</a>
<% end %>
<a href="/rooms/new">New Room</a>

app/views/rooms/new.html.erb
<!-------------CREATE----------------->
<h1>New Room</h1>
<%= form_with model: @room do |form| %>
  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  <div>
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>
  <div>
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :home_type %>
    <%= form.text_field :home_type %>
  </div>
  <div>
    <%= form.label :room_type %>
    <%= form.text_field :room_type %>
  </div>
  <div>
    <%= form.label :total_occupancy %>
    <%= form.number_field :total_occupancy %>
  </div>
  <div>
    <%= form.label :total_bedrooms %>
    <%= form.number_field :total_bedrooms %>
  </div>
  <div>
    <%= form.label :total_bathrooms %>
    <%= form.number_field :total_bathrooms %>
  </div>
    <%= form.submit %>
<% end %>

app/views/rooms/reservations.html.erb
<h1>Reserve Room</h1>
<%= form_for [@room, @reservation], url: reservations_room_path(@room) do |f| %>
  <%= f.label :start_date %>
  <%= f.date_select :start_date %>

  <%= f.label :end_date %>
  <%= f.date_select :end_date %>

  <%= f.submit "Reserve Room" %>
<% end %>

app/views/rooms/show.html.erb
<h1>Room Info</h1>
<h2><%= @room.address %></h2>
<p>City: <%= @room.city %></p>
<p>State: <%= @room.state %></p>
<p>Price: <%= @room.price %></p>
<p>Description: <%= @room.description %></p>
<p>Home Type: <%= @room.home_type %></p>
<p>Room Type: <%= @room.room_type %></p>
<p>Total Occupancy: <%= @room.total_occupancy %></p>
<p>Total Bedrooms: <%= @room.total_bedrooms %></p>
<p>Total Bathrooms: <%= @room.total_bathrooms %></p>
<a href="/rooms/<%= @room.id %>/edit">Edit Room</a>
<a href="/rooms">Back to all Rooms</a>
<a href="/rooms/<%= @room.id %>" data-turbo-method="delete">Destroy Room</a>

<%# <a href="/rooms/reservations">Reserve Room</a> %>
<%= link_to "Reserve Room", reservations_room_path(@room) %>